### ISSUE TITLE
保存上有些问题

### ISSUE THREAD

**Issue by qiujuer** [mycolorway/simditor-autosave#4]
情况是这个，我现在发表一篇文章，此时文章是进行了保存的，当我提交文章后；下次想要再发表时进来发现是上一次的状态。
编辑也是一样，永远看见的都是存储的东西。
而文本框中原本的值总是被存储值覆盖，当编辑的时候，存储框中原本就有值。

建议增加：
- 提交更改后清空存储
- 当文本框中原本含有值时，不读取存储，而是覆盖当前文本框中的值到存储中。

**Comment by farthinker** [comment]
@qiujuer 目前的设计是提交编辑器所在的表单（jquery-ujs的ajax:success事件）会自动清空autosave的缓存，但是如果你们没有使用juqery-ujs的表单来提交编辑器的内容，可以这样手动清除autosave：

```
editor.autosave.storage.remove editor.autosave.path
```

我考虑过把ajax:success事件改成普通的submit事件，但是有个缺点是，提交验证失败缓存还是会被清空
另外你可以给textarea上的`data-autosave`设置不同的name来区分创建和编辑等不同的编辑器

**Comment by qiujuer** [comment]
听你这么一说，算是明白了，多谢啊。
对了我之前弄了一个表情Emoji插件，你可以看看能否加入扩展。
https://github.com/qiujuer/Simditor-PrettyEmoji

这个插件是基于你们官方提供的来的，后面还会继续改进。

**Comment by farthinker** [comment]
感谢，我稍后加上
我让同事评估一下，如果觉得不错就放到tower里面：）

**Comment by qiujuer** [comment]
嗯嗯 多谢了，后面再详细对类别进行分类一下，然后合并小图片，这样预览时会少一些加载，争取更Nice一些。
