### ISSUE TITLE
按照说明设置后，每个文本框的内容都一样了

### ISSUE THREAD

**Issue by unityoxb** [mycolorway/simditor-autosave#6]
有个问题咨询一下：

`data-autosave="editor-content"`
这是这个参数是设成死的还是应该加个变量？像这个：
`data-autosave="editor-content".$blog_id`

加了变量之后正常，否则的话，打开每篇博客，编辑器中的内容都成了一样的了。

**Comment by RuochenLyu** [comment]
那个是缓存的 key，每个编辑器不能一样。

**Comment by unityoxb** [comment]
哦，那就是说，我加变量是正确的对吗？谢谢回答。

**Comment by RuochenLyu** [comment]
yep
unity notifications@github.com于2016年3月29日 周二18:35写道：

**Comment by unityoxb** [comment]
另外请教一下，麻烦你了：这个本地存储，是否需要在表单提交后手动清除呢？

**Comment by unityoxb** [comment]
如果要清除的话，怎样写呢？对这些方面不熟悉。非常感谢！

**Comment by RuochenLyu** [comment]
1. 提交后自动清除的。
2. 内容保存在 `localStorage` 里，直接清除 `localStorage` 对应的内容就可以。
